django_project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/two-factor/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('frontend.urls')),
    path('', include('docs_crawler.urls')),
    path('admin/', admin.site.urls),
    path('', include('notification.urls')),
    path('', include('activity.urls')),
    path('', include('stakeholder.urls')),
    path('', include('sawps.urls')),
    path('', include('species.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

django_project/frontend/urls.py
from django.urls import path, re_path
from frontend.api_views.data_table import DataTableAPIView
from frontend.api_views.map import (
    AerialTile,
    ContextLayerList,
    DefaultPropertiesLayerMVTTiles,
    FindParcelByCoord,
    FindPropertyByCoord,
    MapAuthenticate,
    MapStyles,
    PopulationCountLegends,
    SessionPropertiesLayerMVTTiles,
)
from frontend.api_views.metrics import (
    ActivityPercentageAPIView,
    PopulationPerAgeGroupAPIView,
    PropertiesPerPopulationCategoryAPIView,
    PropertyCountPerAreaCategoryAPIView,
    PropertyCountPerPopulationSizeCategoryAPIView,
    PropertyPerAreaAvailableCategoryAPIView,
    PropertyPerPopDensityCategoryAPIView,
    SpeciesPopulationCountPerYearAPIView,
    SpeciesPopulationCountPerProvinceAPIView,
    SpeciesPopulationDensityPerPropertyAPIView,
    TotalAreaAvailableToSpeciesAPIView,
    TotalAreaPerPropertyTypeAPIView,
    TotalAreaVSAvailableAreaAPIView,
    TotalCountPerActivityAPIView,
    TotalCountPerPopulationEstimateAPIView,
)
from frontend.api_views.national_statistic import (
    NationalActivityCountPerPropertyView,
    NationalActivityCountPerProvinceView,
    NationalActivityCountView,
    NationalPropertiesView,
    NationalSpeciesView,
    NationalStatisticsView,
)
from frontend.api_views.population import (
    DraftPopulationUpload,
    FetchDraftPopulationUpload,
    PopulationMeanSDChartApiView,
    PopulationMetadataList,
    UploadPopulationAPIVIew,
    FetchPopulationData
)
from frontend.api_views.property import (
    CreateNewProperty,
    PropertyDetail,
    PropertyList,
    PropertyMetadataList,
    PropertySearch,
    UpdatePropertyBoundaries,
    UpdatePropertyInformation,
    CheckPropertyNameIsAvailable,
    ListPropertyTypeAPIView,
    ListProvince
)
from frontend.api_views.statistical import (
    DownloadTrendDataAsJson
)
from frontend.api_views.spatial_filter import SpatialFilterList
from frontend.api_views.statistical import SpeciesNationalTrend, SpeciesTrend
from frontend.api_views.upload import (
    BoundaryFileGeoJson,
    BoundaryFileList,
    BoundaryFileRemove,
    BoundaryFileSearch,
    BoundaryFileSearchStatus,
    BoundaryFileUpload,
)
from frontend.views.base_view import get_user_notifications

from .api_views.user import UserInfoAPIView
from .views.about import AboutView
from .views.contact import ContactUsView
from .views.help import HelpView
from .views.home import HomeView
from .views.map import (
    MapView,
    redirect_to_charts,
    redirect_to_explore,
    redirect_to_reports,
    redirect_to_trends,
    redirect_to_upload,
)
from .views.online_form import OnlineFormView
from .views.organisations import (
    OrganisationsView,
    organization_detail,
    save_permissions,
)
from .views.switch_organisation import switch_organisation
from .views.totp_device import (
    add_totp_device, delete_totp_device, view_totp_devices
)
from .views.users import OrganisationUsersView

urlpatterns = [
    re_path(
        r'^api/map/search/parcel/?$',
        FindParcelByCoord.as_view(),
        name='find-parcel'
    ),
    re_path(
        r'^api/map/search/property/?$',
        FindPropertyByCoord.as_view(),
        name='find-property'
    ),
    re_path(
        r'^api/map/search/context_layer/list/?$',
        ContextLayerList.as_view(),
        name='context-layer-list'
    ),
    re_path(
        r'^api/map/styles/?$',
        MapStyles.as_view(),
        name='map-style'
    ),
    re_path(
        r'^api/map/authenticate/?$',
        MapAuthenticate.as_view(),
        name='map-authenticate'
    ),
    re_path(
        r'^api/map/layer/aerial/'
        r'(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+)/?$',
        AerialTile.as_view(),
        name='aerial-map-layer'
    ),
    re_path(
        r'^api/map/layer/properties-session/'
        r'(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+)/?$',
        SessionPropertiesLayerMVTTiles.as_view(),
        name='session-properties-map-layer'
    ),
    re_path(
        r'^api/map/layer/properties/'
        r'(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+)/?$',
        DefaultPropertiesLayerMVTTiles.as_view(),
        name='default-properties-map-layer'
    ),
    re_path(
        r'^api/map/legends/properties/?$',
        PopulationCountLegends.as_view(),
        name='properties-map-legends'
    ),
    re_path(
        r'^api/property/create/?$',
        CreateNewProperty.as_view(),
        name='property-create'
    ),
    re_path(
        r'^api/property/check-available-name/?$',
        CheckPropertyNameIsAvailable.as_view(),
        name='property-check-available-name'
    ),
    re_path(
        r'^api/property/list/(?P<organisation_id>\d+)?/?$',
        PropertyList.as_view(),
        name='property-list'
    ),
    re_path(
        r'^api/property/detail/(?P<id>\d+)/?$',
        PropertyDetail.as_view(),
        name='property-detail'
    ),
    re_path(
        r'^api/property/detail/update/?$',
        UpdatePropertyInformation.as_view(),
        name='property-update-detail'
    ),
    re_path(
        r'^api/property/search/?$',
        PropertySearch.as_view(),
        name='property-search'
    ),
    re_path(
        r'^api/property/types/?$',
        ListPropertyTypeAPIView.as_view(),
        name='property-types'
    ),
    re_path(
        r'^api/province/?$',
        ListProvince.as_view(),
        name='province-list'
    ),
    re_path(
        r'^api/property/boundaries/update/?$',
        UpdatePropertyBoundaries.as_view(),
        name='property-update-boundaries'
    ),
    re_path(
        r'^api/property/metadata/list/?$',
        PropertyMetadataList.as_view(),
        name='property-metadata'
    ),
    re_path(
        r'^api/upload/boundary-file/remove/?$',
        BoundaryFileRemove.as_view(),
        name='boundary-file-remove'
    ),
    re_path(
        r'^api/upload/boundary-file/(?P<session>[\da-f-]+)/list/?$',
        BoundaryFileList.as_view(),
        name='boundary-file-list'
    ),
    re_path(
        r'^api/upload/boundary-file/(?P<session>[\da-f-]+)/search/?$',
        BoundaryFileSearch.as_view(),
        name='boundary-file-search'
    ),
    re_path(
        r'^api/upload/boundary-file/(?P<session>[\da-f-]+)/status/?$',
        BoundaryFileSearchStatus.as_view(),
        name='boundary-file-status'
    ),
    re_path(
        r'^api/upload/boundary-file/(?P<session>[\da-f-]+)/geojson/?$',
        BoundaryFileGeoJson.as_view(),
        name='boundary-file-geojson'
    ),
    re_path(
        r'^api/upload/boundary-file/?$',
        BoundaryFileUpload.as_view(),
        name='boundary-file-upload'
    ),
    re_path(
        r'^api/population/metadata/list/?$',
        PopulationMetadataList.as_view(),
        name='population-metadata'
    ),
    re_path(
        r'^api/upload/population/fetch/(?P<id>\d+)/?$',
        FetchPopulationData.as_view(),
        name='fetch-population-data'
    ),
    re_path(
        r'^api/upload/population/(?P<property_id>\d+)/?$',
        UploadPopulationAPIVIew.as_view(),
        name='population-upload'
    ),
    re_path(
        r'^api/species/(?P<species_id>\d+)/trend/national/?$',
        SpeciesNationalTrend.as_view(),
        name='species-national-trend'
    ),
    path(
        'api/species/population_trend/download/',
        DownloadTrendDataAsJson.as_view(),
        name='download-species-population-trend'
    ),
    path(
        'api/species/population_trend/',
        SpeciesTrend.as_view(),
        name='species-population-trend'
    ),
    path(
        'api/upload/population/draft/<uuid:draft_uuid>/',
        FetchDraftPopulationUpload.as_view(),
        name='fetch-draft-upload-species'
    ),
    path(
        'api/upload/population/draft/<int:property_id>/',
        DraftPopulationUpload.as_view(),
        name='draft-upload-species'
    ),
    path(
        'switch-organisation/<int:organisation_id>/',
        switch_organisation,
        name='switch-organisation'
    ),
    path('map/', MapView.as_view(), name='map'),
    path(
        'reports/',
        redirect_to_reports,
        name='reports'
    ),
    path(
        'charts/',
        redirect_to_charts,
        name='charts'
    ),
    path(
        'trends/',
        redirect_to_trends,
        name='trends'
    ),
    path(
        'upload/',
        redirect_to_upload,
        name='upload'
    ),
    path(
        'explore/',
        redirect_to_explore,
        name='explore'
    ),
    path(
        'upload-data/<int:property_id>/',
        OnlineFormView.as_view(),
        name='online-form'
    ),
    path('help/', HelpView.as_view(), name='help'),
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('users/', OrganisationUsersView.as_view(), name='Users'),
    path(
        'organisations/<str:slug>/',
        OrganisationsView.as_view(),
        name='organisations'
    ),
    path('contact/', ContactUsView.as_view(), name='contact'),
    path('api/data-table/', DataTableAPIView.as_view(), name='data-table'),
    path(
        'api/species-population-count/',
        SpeciesPopulationCountPerYearAPIView.as_view(),
        name='species_population_count'
    ),
    path(
        'api/activity-percentage/',
        ActivityPercentageAPIView.as_view(),
        name='activity_percentage'
    ),
    path(
        'api/total-count-per-activity/',
        TotalCountPerActivityAPIView.as_view(),
        name='total_count_per_activity'
    ),
    path(
        'api/species-population-total-density/',
        SpeciesPopulationDensityPerPropertyAPIView.as_view(),
        name='species_population_total_density'
    ),
    path(
        'api/total-count-per-population-estimate/',
        TotalCountPerPopulationEstimateAPIView.as_view(),
        name='total-count-per-population-estimate'
    ),
    path(
        'api/species-count-per-province/',
        SpeciesPopulationCountPerProvinceAPIView.as_view(),
        name='species_count_per_province'
    ),
    path(

django_project/notification/urls.py
from django.urls import path, include


# api urls
urlpatterns = [  # '',
    path('api/', include('notification.api_urls')),
]

django_project/frontend/models/base_task.py
"""Base model for task.
"""
from django.db import models
from django.utils import timezone

# task statuses
PENDING = 'PENDING'
PROCESSING = 'PROCESSING'
DONE = 'DONE'
ERROR = 'ERROR'


class BaseTaskRequest(models.Model):
    """Abstract class for Base Task Request."""

    class Meta:
        """Meta class for abstract base task request."""
        abstract = True

    STATUS_CHOICES = (
        (PENDING, PENDING),
        (PROCESSING, PROCESSING),
        (DONE, DONE),
        (ERROR, ERROR)
    )

    status = models.CharField(
        max_length=100,
        choices=STATUS_CHOICES,
        default=PENDING
    )

    started_at = models.DateTimeField(
        null=True,
        blank=True
    )

    finished_at = models.DateTimeField(
        null=True,
        blank=True
    )

    task_id = models.CharField(
        null=True,
        blank=True,
        max_length=256
    )

    progress = models.FloatField(
        null=True,
        blank=True
    )

    progress_text = models.TextField(
        null=True,
        blank=True
    )

    errors = models.TextField(
        null=True,
        blank=True
    )

    def task_on_started(self):
        """Initialize properties when task is started."""
        self.status = PROCESSING
        self.started_at = timezone.now()
        self.finished_at = None
        self.progress = 0
        self.progress_text = None
        self.save()

django_project/frontend/models/boundary_search.py
# -*- coding: utf-8 -*-


"""Classes for searching parcels.
"""
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.conf import settings
from frontend.models.base_task import BaseTaskRequest

# uploaded file types
GEOJSON = 'GEOJSON'
SHAPEFILE = 'SHAPEFILE'
GEOPACKAGE = 'GEOPACKAGE'
KML = 'KML'


class BoundaryFile(models.Model):
    """Boundary uploaded file."""

    FILE_TYPE_CHOICES = (
        (GEOJSON, GEOJSON),
        (SHAPEFILE, SHAPEFILE),
        (GEOPACKAGE, GEOPACKAGE),
        (KML, KML)
    )

    session = models.CharField(
        blank=False,
        null=False,
        max_length=256
    )

    meta_id = models.CharField(
        blank=True,
        default='',
        max_length=256
    )

    upload_date = models.DateTimeField(
        null=True,
        blank=True
    )

    file = models.FileField(
        upload_to='boundary_files/%Y/%m/%d/'
    )

    file_type = models.CharField(
        max_length=100,
        blank=False,
        null=False,
        choices=FILE_TYPE_CHOICES
    )

    uploader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    name = models.CharField(
        default='',
        blank=True,
        max_length=512
    )

    def __str__(self):
        return self.name


class BoundarySearchRequest(BaseTaskRequest, gis_models.Model):
    """Boundary search request."""

    type = models.CharField(
        max_length=256,
        help_text='File/Digitise'
    )

    session = models.CharField(
        max_length=256
    )

    request_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    geometry = gis_models.MultiPolygonField(
        srid=4326,
        null=True,
        blank=True
    )

    parcels = models.JSONField(
        default=list,
        null=True,
        blank=True
    )

    used_parcels = models.JSONField(
        default=list,
        null=True,
        blank=True
    )

django_project/frontend/forms.py
from django import forms


class ContactUsForm(forms.Form):
    name = forms.CharField(required=True, max_length=512)
    email = forms.EmailField(required=True)

    subject = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': "form-control", 'style': "height:80px"}),
        required=True
    )

    copy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': "form-check-input"})
    )

    def clean(self):
        cleaned_data = super(ContactUsForm, self).clean()
        return cleaned_data

django_project/frontend/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

django_project/frontend/views/about.py
from .base_view import OrganisationBaseView


class AboutView(OrganisationBaseView):
    """
    AboutView displays the about page by rendering the 'about.html' template.
    """

    template_name = 'about.html'

django_project/frontend/views/contact.py
from django.views.generic.edit import FormView
from frontend.forms import ContactUsForm
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.conf import settings


class ContactUsView(FormView):
    """
    ContactView
    """
    template_name = 'contact.html'
    form_class = ContactUsForm
    success_url = "/"

    def get_initial(self):
        initial = super(ContactUsView, self).get_initial()
        if not self.request.user.is_anonymous:
            initial['name'] = self.request.user.get_full_name()
            initial['email'] = self.request.user.email

        return initial

    def form_valid(self, form):
        form_data = form.cleaned_data

        if not self.request.user.is_anonymous:
            form_data['username'] = self.request.user.username

        subject = form_data['subject']

        # POST to the support email
        recipients = settings.CONTACT_US_RECIPIENTS

        sender = form_data.get('email')
        cc = []
        if form_data['copy']:
            cc.append(sender)

        message = render_to_string(
            'emails/email_contact_us.html',
            {
                'name': form_data['name'],
                'message': form_data['message'],
                'email': form_data['email'],
            },
        )

        email = EmailMultiAlternatives(
            subject,
            message,
            settings.SERVER_EMAIL,
            recipients,
            cc=cc
        )
        email.content_subtype = "html"
        email.send()

        return super(ContactUsView, self).form_valid(form)

django_project/frontend/views/help.py
from .base_view import OrganisationBaseView


class HelpView(OrganisationBaseView):
    """
    HelpView displays the help page by rendering the 'help.html' template.
    """

    template_name = 'help.html'

django_project/frontend/views/home.py
from .base_view import OrganisationBaseView


class HomeView(OrganisationBaseView):
    """
    HomeView displays the home page by rendering the 'home.html' template.
    """

    template_name = 'home.html'

django_project/frontend/templates/about.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}SAWPS - About{% endblock%}

{% block content %}
<section class="about-page fs-background" style="background-color: #000000; min-height:var(--min-content-height);">
    <div class="container-fluid full-height position-absolute">
    <div class="row half-height">
        <div class="col-12 col-md-5 col-lg-4 col-xxl-5"></div>
        <div class="col-12 col-md-7 col-lg-8 col-xxl-7">
            <div class='about-content-title'>
                SOUTH AFRICAN WILDLIFE POPULATION SYSTEM (SAWPS)
            </div>
            <div class='about-subsection-1'>
                <div class='about-subsection-1-video-holder'>
                <iframe src="https://www.youtube.com/embed/EEUg51ptrfw" title="Testing Video 5" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen data-testid='about-page-video-frame' ></iframe>
                </div>
                <div class='about-subsection-1-text about-subsection-1-text2'>
                    <p class="about-text">SAWPS is a centralised wildlife population and trade monitoring system for assessing population trends, abundance and use trends of priority species intended to enable evidence-based policy design and implementation.</p>
                        <p class="about-text">The South African National Biodiversity Institute (SANBI) has a mandate to curate biodiversity information for policy design and implementation. While the South African Wildlife Population System (SAWPS) is intended to collate wildlife population data to assess stocks and sustainable trade, SANBI has a number of other biodiversity databases available to decision-makers and managers.<br><br>
                        <span>Please visit the<a href="https://biodiversityadvisor.sanbi.org"> Biodiversity Advisor </a>for more information</span>
                    </p>
                </div>
            </div>
            <div class='about-subsection-2 about-section'>
                <div class="subsection">
                    <div class="section-img">
                    <img src="/static/images/icons/data-store.png" alt="data"
                    class="img-fluid ml-2" style="width: 80px;">
                    </div>
                    <div class="section-text">
                    <h4 style="margin-top: 0.6%;">Secure species data storage</h4>
                    </div>
                </div>
            </div>
            <div class='about-subsection-3 about-section'>
                <div class="subsection">
                    <div class="section-img">
                    <img src="/static/images/icons/visualisation.png" alt="data"
                    class="img-fluid ml-2" style="width: 80px;">
                    </div>
                    <div class="section-text">
                    <h4 style="margin-top: 0.5%;">automated reporting</h4>
                    </div>
                </div>
            </div>
            <div class='about-subsection-4 about-section'>
                <div class="subsection">
                    <div class="section-img">
                    <img src="/static/images/icons/report.png" alt="data"
                    class="img-fluid ml-2" style="width: 80px;">
                    </div>
                    <div class="section-text">
                    <h4 style="margin-top: 0.5%;">Data analysis and visualisation</h4>
                    </div>
                </div>
            </div>
            <div class='about-subsection-5 about-section'>
                <div class="subsection">
                    <div class="section-img">
                    <img src="/static/images/icons/organisation.png" alt="data"
                    class="img-fluid ml-2" style="width: 80px;">
                    </div>
                    <div class="section-text">
                    <h4 style="margin-top: 0.4%;">Support National Decision making</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

</html>

django_project/frontend/templates/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}SAWPS - Contact{% endblock%}

{% block content %}
<section class="contact-banner-img fs-background" style="background-color: #000000; min-height: var(--min-content-height);">
    <div class="container full-height position-absolute contact-page">
        <div class="row justify-content-center align-items-center full-height">
            <div class="col-lg-4 col-12"></div>
            <div class="col-lg-6 col-md-8 col-sm-10 col-12 sawps-text-primary">
                <div class="account-form content" style="background-color: #111111; ">
                    {% csrf_token %}
                    <div class="container">
                        <div class="custom-form-container">
                            <h4 class="account-form-title">{% trans "Contact Us" %}</h4>
                            <hr class="separator">
                            <form class="contact" action="{% url 'contact' %}" method="post" name="contact">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_name">Name</label>
                                    <input id="id_name" name="name" type="text" class="form-control"
                                        value="{% if form.data.name %}{{form.data.name}}{% else %}{{form.initial.name}}{% endif %}" />
                                </div>

                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input id="id_email" name="email" type="text" class="form-control" />
                                </div>

                                <div class="form-group">
                                    <label for="id_subject">Subject</label>
                                    {{form.subject}}
                                </div>

                                <div class="form-group">
                                    <label for="id_message">Message</label>
                                    {{form.message}}
                                </div>
                                <div class="form-group float-left">
                                    <div class="form-check">
                                        {{form.copy}}
                                        <label class="form-check-label" for="id_copy">
                                            Send me a copy
                                        </label>
                                    </div>
                                </div>
                                <button id="submit-button" class="sawps-from-submit account-button float-right"
                                    type="submit">{% trans "Send" %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

django_project/frontend/templates/help.html
{% extends "base.html" %}
{% block extra_head %}
    {% load render_bundle from webpack_loader %}
{% endblock %}
{% block head_title %}SAWPS - Help{% endblock%}


{% block content %}
    <script>
      window.maptiler_api_key = "{{ maptiler_api_key }}";
    </script>

    <div id="app"></div>
    {% render_bundle 'Help' 'js' %}
    {% render_bundle 'Home' 'css' %}

{% endblock %}
{% block footer %}
{% endblock %}

</html>

django_project/frontend/templates/home.html
{% extends "base.html" %}
{% block extra_head %}
    {% load render_bundle from webpack_loader %}
{% endblock %}


{% block content %}


<div id="app"></div>
{% render_bundle 'Home' 'js' %}
{% render_bundle 'Home' 'css' %}

{% endblock %}
{% block footer %}
{% endblock %}

</html>

django_project/frontend/templates/map.html
{% extends "base.html" %}
{% block extra_head %}
    {% load render_bundle from webpack_loader %}
{% endblock %}


{% block content %}
<script>
    window.maptiler_api_key = "{{ maptiler_api_key }}";
</script>

<div id="app"></div>
{% render_bundle 'Home' 'css' %}
{% render_bundle 'Main' 'js' %}

{% endblock %}
{% block footer %}
{% endblock %}

</html>

django_project/frontend/templates/modal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'js/bootstrap-4.3.1/css/bootstrap.min.css' %}">
    <title>{% block head_title %}Kartoza{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/maplibre-gl@2.1.9/dist/maplibre-gl.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-...">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block extra_head %}
    {% endblock %}
</head>

<script>
  window.csrfToken = "{{ csrf_token }}";
  window.isLoggedIn = {% if user.is_authenticated %}true{% else %}false{% endif %};
</script>
<body>
{% block header %}
{% include 'navibar.html' %}
{% endblock %}

{% block content %}
{% endblock %}
</body>
</html>

django_project/frontend/templates/online_form.html
{% extends "base.html" %}
{% block extra_head %}
    {% load render_bundle from webpack_loader %}
{% endblock %}
{% block head_title %}SAWPS - Data Upload OnlineForm{% endblock %}


{% block content %}
<script>
    window.maptiler_api_key = "{{ maptiler_api_key }}";
    window.property_id = "{{ property_id }}";
    window.upload_id = "{{ upload_id }}";
</script>

<div id="app"></div>
{% render_bundle 'Home' 'css' %}
{% render_bundle 'OnlineForm' 'js' %}

{% endblock %}
{% block footer %}
{% endblock %}

</html>